MVC/MVC/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls')),
]

MVC/mainsite/urls.py
from django.urls import path

from . import views

app_name='mainsite'
urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('about/',views.about,name='about'),
    path('list/',views.show_list,name='list'),
    path('list/order=<order>/',views.show_list,name='order_list'),
    path('list/filter=<filter>/',views.show_list,name='filter_list'),
    path('list/<sku>/',views.detail,name='detail'),
]

MVC/mainsite/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    sku=models.SlugField(primary_key=True)
    name=models.CharField(max_length=20)
    price=models.PositiveIntegerField()
    sizes=(
        ('S','Small'),
        ('M','Medium'),
        ('L','Large'),
    )
    size=models.CharField(max_length=1,choices=sizes)
    inventory=models.PositiveIntegerField()

MVC/mainsite/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404
import datetime,random
from .models import Product

def homepage(request):
	template=loader.get_template('index.html')
	quotes=['xxxxxxxx','yyyyyyyyyyyy']
	html=template.render({'quote':random.choice(quotes)}).encode()
	return HttpResponse(html)

def about(request):
	template=loader.get_template('about.html')
	html=template.render().encode()
	return HttpResponse(html)

def show_list(request,order='sku',filter=''):
	products=Product.objects.order_by(order).filter(name__contains=filter)
	template=loader.get_template('list.html')
	html=template.render(locals()).encode()
	return HttpResponse(html)

def detail(request,sku):
	product=get_object_or_404(Product,sku=sku)
	template=loader.get_template('detail.html')
	html=template.render(locals()).encode()
	return HttpResponse(html)

MVC/mainsite/templates/about.html
<!DOCTYPE html>
  <html>
  <head>
   <meta charset='utf-8'>
   <title>
   关于我自己 
   </title>
  </head>
  <body>
   <h2>Hello</h2>
   <hr>
   <p>
     Nice to meet you!
   </p>
   <a href="{%url 'mainsite:homepage'%}">回首页</a>
  </body>
  </html>

MVC/mainsite/templates/detail.html
<!DOCTYPE html>
  <html>
  <head>
   <meta charset='utf-8'>
   <title>
   {{ product.name }}
   </title>
  </head>
  <body>
   <h2>{{ product.name }}</h2>
   <hr>
    <table width=400 border=1 bgcolor='#ccffcc'>
   <tr><td>产品编号</td><td>{{product.sku}}</td></tr>
   <tr><td>产品名称</td><td>{{product.name}}</td></tr>
   <tr><td>二手售价</td><td>{{product.price}}</td></tr>
   <tr><td>库存数量</td><td>{{product.inventory}}</td></tr>
   </table>
   <a href ="{%url 'mainsite:list'%}"> 返回列表 </a>
  </body>
  </html>

MVC/mainsite/templates/index.html
<!DOCTYPE html>
  <html>
  <head>
   <meta charset='utf-8'>
   <title>
   欢迎来到我的网站
   </title>
      <style>
          .bandlist li
          {
              #display: inline-block;
              margin-right: 5px;
          }
      </style>
  </head>
  <body>
   <h2>欢迎来到我的网站</h2>
   <hr>
   <ul>
    <li><a href="{%url 'mainsite:list'%}">二手手机列表</a>
        <ul class="bandlist">
            <li><a href="{%url 'mainsite:filter_list' 'Sony'%}">Sony</a></li>
            <li><a href="{%url 'mainsite:filter_list' 'SamSung'%}">SamSung</a></li>
            <li><a href="{%url 'mainsite:filter_list' 'HTC'%}">HTC</a></li>
        </ul>
     </li>
	<li><a href="{%url 'mainsite:about'%}">关于我</a></li>
   </ul>
   <em>今日佳句：{{quote}}</em>
  </body>
  </html>

MVC/mainsite/templates/list.html
<!DOCTYPE html>
  <html>
  <head>
   <meta charset='utf-8'>
   <title>
   手机列表
   </title>
  </head>
  <body>
    <h2> 以下是目前本店销售中的二手手机列表 </h2>
    <hr>
    排序:
    <a href = "{%url 'mainsite:order_list' 'price'%}">按售价&#129031;</a>
    <a href = "{%url 'mainsite:order_list' '-price'%}">&#129029;</a>
    <a href = "{%url 'mainsite:order_list' 'size'%}">按尺寸&#129031;</a>
    <a href = "{%url 'mainsite:order_list' '-size'%}">&#129029;</a>
    <a href = "{%url 'mainsite:order_list' 'inventory'%}">按库存&#129031;</a>
    <a href = "{%url 'mainsite:order_list' '-inventory'%}">&#129029;</a>
    <table width=400 border=1 bgcolor='#ccffcc'>
    <tr><td>产品名称</td><td>售价</td><td>库存量</td></tr>
      {% for product in products %}
	     <tr>
		   <td><a href="{%url 'mainsite:detail' product.sku%}">{{product.name}}</a></td>
		   <td>{{product.price}}</td>
		   <td>{{product.inventory}}</td>
		 </tr>
      {% endfor %}
   </table>
  <a href="{%url 'mainsite:homepage'%}">回首页</a>
  </body>
  </html>