blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls')),
]

blog/mainsite/urls.py
from django.urls import path

from . import views

app_name='mainsite'
urlpatterns = [
    path('',views.home_page,name='homepage'),
    path('post/<slug:post_slug>/',views.show_post,name='post'),
    path('post/<slug:post_slug>/like/',views.post_like_post,name='post_like_post'),
    path('post/<slug:post_slug>/dislike/',views.post_dislike_post,name='post_dislike_post'),
    path('video/',views.video,name='video_first'),
    path('video/<slug:video_slug>/',views.video,name='video'),
    path('<int:a>+<int:b>=/',views.sum),
    path('trans/<int:n><type>/',views.trans),
]

blog/mainsite/models.py
from django.db import models

# Create your models here.

from django.utils import timezone

class Post(models.Model):
    title=models.CharField(max_length=256)
    slug=models.SlugField()
    body=models.TextField()
    pub_date=models.DateTimeField(default=timezone.now)
    like_count=models.IntegerField(default=0)

    class Meta:
        ordering=('-like_count',)
    
    def __str__(self):
        return self.title

class Video(models.Model):
    title=models.CharField(max_length=256)
    slug=models.SlugField()
    src=models.CharField(max_length=256)
    pub_date=models.DateTimeField(default=timezone.now)

    class Meta:
        ordering=('-pub_date',)
    
    def __str__(self):
        return self.title

blog/mainsite/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.shortcuts import get_object_or_404
import datetime
from . import models

def home_page(request):
    posts=models.Post.objects.all()
    template=loader.get_template('index.html')
    now=datetime.datetime.now()
    html=template.render(locals()).encode()
    return HttpResponse(html)

def show_post(request,post_slug):
    template=loader.get_template('post.html')
    post=get_object_or_404(models.Post,slug=post_slug)
    html=template.render(locals()).encode()
    return HttpResponse(html)

def post_like_post(request,post_slug):
    post=get_object_or_404(models.Post,slug=post_slug)
    post.like_count+=1
    post.save()
    return HttpResponseRedirect(reverse('mainsite:post', args=(post_slug,)))
def post_dislike_post(request,post_slug):
    post=get_object_or_404(models.Post,slug=post_slug)
    post.like_count-=1
    post.save()
    return HttpResponseRedirect(reverse('mainsite:post', args=(post_slug,)))


def video(request,video_slug='first'):
    template=loader.get_template('video_index.html')
    video_list=models.Video.objects.all()
    now=datetime.datetime.now()
    if video_slug=='first':
        return HttpResponseRedirect(reverse('mainsite:video', args=(video_list[0].slug,)))
    else:
        video=get_object_or_404(models.Video,slug=video_slug)
        html=template.render(locals()).encode()
        return HttpResponse(html)


def sum(request,a,b):
    html=str(a)+'+'+str(b)+'='+str(a+b)
    return HttpResponse(html)
def trans(request,n,type):
    if type=='cm':
        html=str(n)+type+'='+str(round(n/2.54,2))+'in'
    if type=='in':
        html=str(n)+type+'='+str(round(n*2.54,2))+'cm'
    return HttpResponse(html)

blog/mainsite/templates/BootstrapNavDemo.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Bootstrap 实例</title>
	<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
	<div class="navbar-header">
		<a class="navbar-brand" href="#">开发技术</a>
	</div>
	<div>
		<ul class="nav navbar-nav">
			<li class="active"><a href="#">C</a></li>
			<li><a href="#">C#</a></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Python
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a href="#">Python基础</a></li>
					<li class="divider"></li>
					<li><a href="#">Python Web开发</a></li>										
					<li><a href="#">Python数据分析</a></li>
					<li class="divider"></li>
					<li><a href="#">Python爬虫</a></li>
				</ul>
			</li>
		</ul>
	</div>
	</div>
</nav>
</body>
</html>

blog/mainsite/templates/base.html
<!-- base.html-->
<!DOCTYPE html>
<html>
<head>
 <meta charset='utf-8'>
 <title>
   {% block title %}{% endblock %}
 </title>
<!--使用block指令设置替换区域名称和位置-->
<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
<script  src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script  src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
  <div class='container-fluid'> <!-- container-fluid自动设置为外层容器的100%-->
  {% include 'header.html' %}<!--使用inclue指令导入指定的模板文件-->
   <div class='row'> <!--row是容器，网格样式要放在row容器里面-->
            <div class='col-sm-4 col-md-4'>  <!--与在同一row中的其他div划分所占列比例，共分4+8=12列，此div占4列-->
                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        <h3>
                            MENU
                        </h3>
                    </div>
                    <div class='panel-body'>
                        <div class='list-group'>
                          <a href="{%url 'mainsite:homepage'%}" class='list-group-item'>主页</a>
                          <a href="{%url 'mainsite:video_first'%}" class='list-group-item'>视频</a>
                          <a href="/admin" class='list-group-item'>管理页面 </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class='col-sm-8 col-md-8'>
                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        {% block headmessage %} {% endblock %}
                    </div>
                    <div class='panel-body'>
                        {% block content %} {% endblock %}
                    </div>
                    <div class='panel-footer'>
                        {% include 'footer.html' %}
                    </div>
                </div>
            </div>
         </div>
  </div>


</body>
</html>

blog/mainsite/templates/footer.html
{% block footer %}
	{% if now %}
		<p>{{now}}</p>
	{% elif post.pub_date %}
		<p>{{post.pub_date}}</p>
	{% else %}
		<p>everything is form internet</p>
	{% endif %}
{% endblock %}

blog/mainsite/templates/header.html
<h1>many posts</h1>
{% load static %}
<div class='well'>
	<img src="{% static 'mainsite/Cycling_Icon_BG.png' %}" style="height: 100pt">
</div>

blog/mainsite/templates/index.html
{% extends 'base.html' %}
{% block title%}welcome to blog{% endblock %}
{% block headmessage %}
    <h3>posts:</a>
{% endblock %}
{% block content %}
    {% for post in posts %}
        <p style='font-size: 14pt;font-weight: bold;'>
            <a href="{%url 'mainsite:post' post.slug%}">{{post.title}}</a>
        </p>
    {% endfor %}
{% endblock %}

blog/mainsite/templates/like.html
<a href="{%url 'mainsite:post_like_post' post.slug%}">&#128077;</a>
{{post.like_count}}
<a href="{%url 'mainsite:post_dislike_post' post.slug%}">&#128078;</a>

blog/mainsite/templates/post.html
{% extends 'base.html' %}
{% block title%}post:{{post.slug}}{% endblock %}
{% block headmessage %}
    <h3>{{post.title}}</a>
    <a href="{%url 'mainsite:homepage'%}">homepage</a>
{% endblock %}
{% block content %}
    <p style='font-size: 12pt;letter-spacing:2pt;'>
        {{post.body}}</a>
    </p>
    {% include 'like.html' %}
{% endblock %}

blog/mainsite/templates/video_base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<style>
	.navbar-brand{
	   padding:0 15px;
	}
	</style>
</head>
<body>
    <nav class='navbar navbar-default'>
        <div class='container-fluid'>
            <div class='navbar-header' >
                <div class='navbar-brand' align=center >
                    {% load staticfiles %}
                    <img src="{% static "mainsite/Cycling_Icon_BG.png" %}" height=100% >
                    
                </div>
            </div>
            {% block menu %}{% endblock %} 
			
        </div>
    </nav>
	
	正在播放 {% block video_title %}{% endblock %}
	
    {% block content %}{% endblock %}
	
    <div class='panel panel-default'>
      <div class='panel-footer'><em>{{ now }}</em></div>
    </div>
  {% include "footer.html" %}
</body>
</html>

blog/mainsite/templates/video_index.html
{% extends 'video_base.html' %}
{% block title %}电影播放{% endblock %}
{% block video_title %}{{video.title}}{% endblock %}
{% block menu %}
	<ul class='nav navbar-nav'>
		<li><a href="{%url 'mainsite:homepage'%}">主页</a></li>
		{% for video in video_list %}
			<li>
				<a href="{% url 'mainsite:video' video.slug%}">
					{{video.title}}
				</a>
			</li>
		{% endfor %}
		<!-- <li>
			<a href="#">英文电影</a>
		</li> -->
	</ul>
{% endblock %}
{% block content %}
	<div class='conatiner'>
		<div id='video_code' align='center'>
			<iframe src="{{video.src}}" width=1416 height=797 frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen> </iframe>
		</div>
	</div>
{% endblock %}