django_blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path

from . import views

app_name='blog'
urlpatterns = [
    path('',views.home_page,name='homepage'),
    path('<post_name>/',views.show_post,name='post'),
    path('<post_name>/like/',views.post_like_post,name='post_like_post'),
    path('<post_name>/dislike/',views.post_dislike_post,name='post_dislike_post'),
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('blog/', include('blog.urls')),
]

django_blog/blog/views.py
from django.shortcuts import render
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.shortcuts import get_object_or_404
import datetime
from .models import Post

def home_page(request):
    posts=Post.objects.all()
    template=loader.get_template('index.html')
    now=datetime.datetime.now()
    html=template.render(locals()).encode()
    return HttpResponse(html)

def show_post(request,post_name):
    template=loader.get_template('post.html')
    post=get_object_or_404(Post,slug=post_name)
    html=template.render(locals()).encode()
    return HttpResponse(html)

def post_like_post(request,post_name):
    post=get_object_or_404(Post,slug=post_name)
    post.like_count+=1
    post.save()
    return HttpResponseRedirect(reverse('blog:post', args=(post_name,)))
def post_dislike_post(request,post_name):
    post=get_object_or_404(Post,slug=post_name)
    post.like_count-=1
    post.save()
    return HttpResponseRedirect(reverse('blog:post', args=(post_name,)))

django_blog/blog/templates/base.html
<!-- base.html-->
<!DOCTYPE html>
<html>
<head>
 <meta charset='utf-8'>
 <title>
   {% block title %}{% endblock %}
 </title>
<!--使用block指令设置替换区域名称和位置-->
<link rel="stylesheet"
href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
<script  src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script  src=
"http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
  <div class='container-fluid'> <!-- container-fluid自动设置为外层容器的100%-->
  {% include 'header.html' %}<!--使用inclue指令导入指定的模板文件-->
   <div class='row'> <!--row是容器，网格样式要放在row容器里面-->
            <div class='col-sm-4 col-md-4'>  <!--与在同一row中的其他div划分所占列比例，共分4+8=12列，此div占4列-->
                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        <h3>
                            MENU
                        </h3>
                    </div>
                    <div class='panel-body'>
                        <div class='list-group'>
                          <a href="{%url 'blog:homepage'%}" class='list-group-item'>HOME</a>
                          <a href="/admin" class='list-group-item'>管理页面 </a>
                          <a href="{%url 'blog:homepage'%}" class='list-group-item'>实时新闻</a>
                          <a href="{%url 'blog:homepage'%}" class='list-group-item'>电视新闻</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class='col-sm-8 col-md-8'>
                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        {% block headmessage %} {% endblock %}
                    </div>
                    <div class='panel-body'>
                        {% block content %} {% endblock %}
                    </div>
                    <div class='panel-footer'>
                        {% include 'footer.html' %}
                    </div>
                </div>
            </div>
         </div>
  </div>


</body>
</html>

django_blog/blog/templates/index.html
{% extends 'base.html' %}
{% block title%}welcome to blog{% endblock %}
{% block headmessage %}
    <h3>posts:</a>
{% endblock %}
{% block content %}
    {% for post in posts %}
        <p style='font-size: 14pt;font-weight: bold;'>
            <a href="{%url 'blog:post' post.slug%}">{{post.title}}</a>
        </p>
    {% endfor %}
{% endblock %}

django_blog/blog/templates/post.html
{% extends 'base.html' %}
{% block title%}post:{{post.slug}}{% endblock %}
{% block headmessage %}
    <h3>{{post.title}}</a>
    <a href="{%url 'blog:homepage'%}">homepage</a>
{% endblock %}
{% block content %}
    <p style='font-size: 12pt;letter-spacing:2pt;'>
        {{post.body}}</a>
    </p>
    {% include 'like.html' %}
{% endblock %}